version: 2
jobs:
  build:
    working_directory: ~/omise/omise-android
    docker:
      - image: circleci/android:api-28
    environment:
      JVM-OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sdk/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sdk/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint testDebug
      - store_artifacts:
          path: sdk/build/reports
          destination: reports
      - store_test_results:
          path: sdk/build/test-results
