env:
  APP_NAME: "3ds-android-sdk"
  REGISTRY: "534625442569.dkr.ecr.ap-southeast-1.amazonaws.com"
steps:
  - label: ":female-police-officer: Dependency Check"
    agents:
      queue: omise
      test-runner: true
    command: .buildkite/check_libs.sh
    artifact_paths: "odc-reports/*"

  - wait

  - label : "Download report artifact"
    agents:
      queue: omise
      docker-builder: true
    command: "mkdir -p /var/lib/buildkite-agent/odc-reports && buildkite-agent artifact download 'odc-reports/*' '/var/lib/buildkite-agent/odc-reports'"

  - wait

  - label : ":sonarqube: Sonarqube"
    agents:
      queue: omise
      docker-builder: true
    branches: "master" # only report on the master branch
    key: use-sonarqube
    plugins:
      - docker#v3.7.0:
          image: 534625442569.dkr.ecr.ap-southeast-1.amazonaws.com/sonar-scanner-cli:latest
          environment:
            - "SONAR_HOST_URL=https://sonar.apps.omise.co"
            - "SONAR_TOKEN"
          volumes:
            - /var/lib/buildkite-agent/odc-reports:/odc-reports
          command: ["sonar-scanner", "-Dsonar.projectKey=${BUILDKITE_PIPELINE_NAME}", "-Dsonar.dependencyCheck.htmlReportPath=/odc-reports/dependency-check-report.html", "-Dsonar.dependencyCheck.xmlReportPath=/odc-reports/dependency-check-report.xml", "-Dsonar.dependencyCheck.jsonReportPath=/odc-reports/dependency-check-report.json", "-Dsonar.dependencyCheck.securityHotspot=true"]

  - label: "Unit Test"
    command: ./gradlew threeds:testDebugUnitTest
    artifact_paths:
      - ".buildkite/artifacts/**/*"
    plugins:
      - docker-compose#v3.2.0:
          run: unit-test
          config:
            - .buildkite/unit-test/docker-compose.yml
    agents:
      queue: omise
      docker-builder: true