package co.omise.android.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class CountryInfo(val name: String, val code: String) : Parcelable {
    companion object {
        val ALL =
            listOf(
                CountryInfo(name = "Afghanistan", code = "AF"),
                CountryInfo(name = "Åland Islands", code = "AX"),
                CountryInfo(name = "Albania", code = "AL"),
                CountryInfo(name = "Algeria", code = "DZ"),
                CountryInfo(name = "American Samoa", code = "AS"),
                CountryInfo(name = "Andorra", code = "AD"),
                CountryInfo(name = "Angola", code = "AO"),
                CountryInfo(name = "Anguilla", code = "AI"),
                CountryInfo(name = "Antarctica", code = "AQ"),
                CountryInfo(name = "Angola", code = "AO"),
                CountryInfo(name = "Antigua and Barbuda", code = "AG"),
                CountryInfo(name = "Argentina", code = "AR"),
                CountryInfo(name = "Armenia", code = "AM"),
                CountryInfo(name = "Aruba", code = "AW"),
                CountryInfo(name = "Australia", code = "AU"),
                CountryInfo(name = "Austria", code = "AT"),
                CountryInfo(name = "Azerbaijan", code = "AZ"),
                CountryInfo(name = "Bahamas", code = "BS"),
                CountryInfo(name = "Bahrain", code = "BH"),
                CountryInfo(name = "Bangladesh", code = "BD"),
                CountryInfo(name = "Barbados", code = "BB"),
                CountryInfo(name = "Belarus", code = "BY"),
                CountryInfo(name = "Belgium", code = "BE"),
                CountryInfo(name = "Belize", code = "BZ"),
                CountryInfo(name = "Benin", code = "BJ"),
                CountryInfo(name = "Bermuda", code = "BM"),
                CountryInfo(name = "Bhutan", code = "BT"),
                CountryInfo(name = "Bolivia (Plurinational State of)", code = "BO"),
                CountryInfo(name = "Bonaire Sint Eustatius Saba", code = "BQ"),
                CountryInfo(name = "Bosnia and Herzegovina", code = "BA"),
                CountryInfo(name = "Botswana", code = "BW"),
                CountryInfo(name = "Bouvet Island", code = "BV"),
                CountryInfo(name = "Brazil", code = "BR"),
                CountryInfo(name = "British Indian Ocean Territory", code = "IO"),
                CountryInfo(name = "Brunei Darussalam", code = "BN"),
                CountryInfo(name = "Bulgaria", code = "BG"),
                CountryInfo(name = "Burkina Faso", code = "BF"),
                CountryInfo(name = "Burundi", code = "BI"),
                CountryInfo(name = "Cabo Verde", code = "CV"),
                CountryInfo(name = "Cambodia", code = "KH"),
                CountryInfo(name = "Cameroon", code = "CM"),
                CountryInfo(name = "Canada", code = "CA"),
                CountryInfo(name = "Cayman Islands", code = "KY"),
                CountryInfo(name = "Central African Republic", code = "CF"),
                CountryInfo(name = "Chad", code = "TD"),
                CountryInfo(name = "Chile", code = "CL"),
                CountryInfo(name = "China", code = "CN"),
                CountryInfo(name = "Christmas Island", code = "CX"),
                CountryInfo(name = "Cocos (Keeling) Islands", code = "CC"),
                CountryInfo(name = "Colombia", code = "CO"),
                CountryInfo(name = "Comoros", code = "KM"),
                CountryInfo(name = "Congo", code = "CG"),
                CountryInfo(name = "Congo, Democratic Republic of the", code = "CD"),
                CountryInfo(name = "Cook Islands", code = "CK"),
                CountryInfo(name = "Costa Rica", code = "CR"),
                CountryInfo(name = "Côte d\"Ivoire", code = "CI"),
                CountryInfo(name = "Croatia", code = "HR"),
                CountryInfo(name = "Cuba", code = "CU"),
                CountryInfo(name = "Curaçao", code = "CW"),
                CountryInfo(name = "Cyprus", code = "CY"),
                CountryInfo(name = "Czechia", code = "CZ"),
                CountryInfo(name = "Denmark", code = "DK"),
                CountryInfo(name = "Djibouti", code = "DJ"),
                CountryInfo(name = "Dominica", code = "DM"),
                CountryInfo(name = "Dominican Republic", code = "DO"),
                CountryInfo(name = "Ecuador", code = "EC"),
                CountryInfo(name = "Egypt", code = "EG"),
                CountryInfo(name = "El Salvador", code = "SV"),
                CountryInfo(name = "Equatorial Guinea", code = "GQ"),
                CountryInfo(name = "Eritrea", code = "ER"),
                CountryInfo(name = "Estonia", code = "EE"),
                CountryInfo(name = "Eswatini", code = "SZ"),
                CountryInfo(name = "Ethiopia", code = "ET"),
                CountryInfo(name = "Falkland Islands", code = "FK"),
                CountryInfo(name = "Faroe Islands", code = "FO"),
                CountryInfo(name = "Fiji", code = "FJ"),
                CountryInfo(name = "Finland", code = "FI"),
                CountryInfo(name = "France", code = "FR"),
                CountryInfo(name = "French Guiana", code = "GF"),
                CountryInfo(name = "French Polynesia", code = "PF"),
                CountryInfo(name = "French Southern Territories", code = "TF"),
                CountryInfo(name = "Gabon", code = "GA"),
                CountryInfo(name = "Gambia", code = "GM"),
                CountryInfo(name = "Georgia", code = "GE"),
                CountryInfo(name = "Germany", code = "DE"),
                CountryInfo(name = "Ghana", code = "GH"),
                CountryInfo(name = "Gibraltar", code = "GI"),
                CountryInfo(name = "Greece", code = "GR"),
                CountryInfo(name = "Greenland", code = "GL"),
                CountryInfo(name = "Grenada", code = "GD"),
                CountryInfo(name = "Guadeloupe", code = "GP"),
                CountryInfo(name = "Guam", code = "GU"),
                CountryInfo(name = "Guatemala", code = "GT"),
                CountryInfo(name = "Guernsey", code = "GG"),
                CountryInfo(name = "Guinea", code = "GN"),
                CountryInfo(name = "Guinea-Bissau", code = "GW"),
                CountryInfo(name = "Guyana", code = "GY"),
                CountryInfo(name = "Haiti", code = "HT"),
                CountryInfo(name = "Heard Island and McDonald Islands", code = "HM"),
                CountryInfo(name = "Holy See", code = "VA"),
                CountryInfo(name = "Honduras", code = "HN"),
                CountryInfo(name = "Hong Kong", code = "HK"),
                CountryInfo(name = "Hungary", code = "HU"),
                CountryInfo(name = "Iceland", code = "IS"),
                CountryInfo(name = "India", code = "IN"),
                CountryInfo(name = "Indonesia", code = "ID"),
                CountryInfo(name = "Iraq", code = "IQ"),
                CountryInfo(name = "Ireland", code = "IE"),
                CountryInfo(name = "Isle of Man", code = "IM"),
                CountryInfo(name = "Israel", code = "IL"),
                CountryInfo(name = "Italy", code = "IT"),
                CountryInfo(name = "Jamaica", code = "JM"),
                CountryInfo(name = "Japan", code = "JP"),
                CountryInfo(name = "Jersey", code = "JE"),
                CountryInfo(name = "Jordan", code = "JO"),
                CountryInfo(name = "Kazakhstan", code = "KZ"),
                CountryInfo(name = "Kenya", code = "KE"),
                CountryInfo(name = "Kiribati", code = "KI"),
                CountryInfo(name = "Korea, Republic of", code = "KR"),
                CountryInfo(name = "Kuwait", code = "KW"),
                CountryInfo(name = "Kyrgyzstan", code = "KG"),
                CountryInfo(name = "Lao People\"s Democratic Republic", code = "LA"),
                CountryInfo(name = "Latvia", code = "LV"),
                CountryInfo(name = "Lebanon", code = "LB"),
                CountryInfo(name = "Lesotho", code = "LS"),
                CountryInfo(name = "Liberia", code = "LR"),
                CountryInfo(name = "Libya", code = "LY"),
                CountryInfo(name = "Liechtenstein", code = "LI"),
                CountryInfo(name = "Lithuania", code = "LT"),
                CountryInfo(name = "Luxembourg", code = "LU"),
                CountryInfo(name = "Macao", code = "MO"),
                CountryInfo(name = "Madagascar", code = "MG"),
                CountryInfo(name = "Malawi", code = "MW"),
                CountryInfo(name = "Malaysia", code = "MY"),
                CountryInfo(name = "Maldives", code = "MV"),
                CountryInfo(name = "Mali", code = "ML"),
                CountryInfo(name = "Malta", code = "MT"),
                CountryInfo(name = "Marshall Islands", code = "MH"),
                CountryInfo(name = "Martinique", code = "MQ"),
                CountryInfo(name = "Mauritania", code = "MR"),
                CountryInfo(name = "Mauritius", code = "MU"),
                CountryInfo(name = "Mayotte", code = "YT"),
                CountryInfo(name = "Mexico", code = "MX"),
                CountryInfo(name = "Micronesia (Federated States of)", code = "FM"),
                CountryInfo(name = "Moldova, Republic of", code = "MD"),
                CountryInfo(name = "Monaco", code = "MC"),
                CountryInfo(name = "Mongolia", code = "MN"),
                CountryInfo(name = "Montenegro", code = "ME"),
                CountryInfo(name = "Montserrat", code = "MS"),
                CountryInfo(name = "Morocco", code = "MA"),
                CountryInfo(name = "Mozambique", code = "MZ"),
                CountryInfo(name = "Myanmar", code = "MM"),
                CountryInfo(name = "Namibia", code = "NA"),
                CountryInfo(name = "Nauru", code = "NR"),
                CountryInfo(name = "Nepal", code = "NP"),
                CountryInfo(name = "Netherlands", code = "NL"),
                CountryInfo(name = "New Caledonia", code = "NC"),
                CountryInfo(name = "New Zealand", code = "NZ"),
                CountryInfo(name = "Nicaragua", code = "NI"),
                CountryInfo(name = "Niger", code = "NE"),
                CountryInfo(name = "Nigeria", code = "NG"),
                CountryInfo(name = "Niue", code = "NU"),
                CountryInfo(name = "Norfolk Island", code = "NF"),
                CountryInfo(name = "Northern Mariana Islands", code = "MP"),
                CountryInfo(name = "North Macedonia", code = "MK"),
                CountryInfo(name = "Norway", code = "NO"),
                CountryInfo(name = "Oman", code = "OM"),
                CountryInfo(name = "Pakistan", code = "PK"),
                CountryInfo(name = "Palau", code = "PW"),
                CountryInfo(name = "Palestine, State of", code = "PS"),
                CountryInfo(name = "Panama", code = "PA"),
                CountryInfo(name = "Papua New Guinea", code = "PG"),
                CountryInfo(name = "Paraguay", code = "PY"),
                CountryInfo(name = "Peru", code = "PE"),
                CountryInfo(name = "Philippines", code = "PH"),
                CountryInfo(name = "Pitcairn", code = "PN"),
                CountryInfo(name = "Poland", code = "PL"),
                CountryInfo(name = "Portugal", code = "PT"),
                CountryInfo(name = "Puerto Rico", code = "PR"),
                CountryInfo(name = "Qatar", code = "QA"),
                CountryInfo(name = "Réunion", code = "RE"),
                CountryInfo(name = "Romania", code = "RO"),
                CountryInfo(name = "Russian Federation", code = "RU"),
                CountryInfo(name = "Rwanda", code = "RW"),
                CountryInfo(name = "Saint Barthélemy", code = "BL"),
                CountryInfo(name = "Saint Helena Ascension Island Tristan da Cunha", code = "SH"),
                CountryInfo(name = "Saint Kitts and Nevis", code = "KN"),
                CountryInfo(name = "Saint Lucia", code = "LC"),
                CountryInfo(name = "Saint Martin (French part)", code = "MF"),
                CountryInfo(name = "Saint Pierre and Miquelon", code = "PM"),
                CountryInfo(name = "Saint Vincent and the Grenadines", code = "VC"),
                CountryInfo(name = "Samoa", code = "WS"),
                CountryInfo(name = "San Marino", code = "SM"),
                CountryInfo(name = "Sao Tome and Principe", code = "ST"),
                CountryInfo(name = "Saudi Arabia", code = "SA"),
                CountryInfo(name = "Senegal", code = "SN"),
                CountryInfo(name = "Serbia", code = "RS"),
                CountryInfo(name = "Seychelles", code = "SC"),
                CountryInfo(name = "Sierra Leone", code = "SL"),
                CountryInfo(name = "Singapore", code = "SG"),
                CountryInfo(name = "Sint Maarten", code = "SX"),
                CountryInfo(name = "Slovakia", code = "SK"),
                CountryInfo(name = "Slovenia", code = "SI"),
                CountryInfo(name = "Solomon Islands", code = "SB"),
                CountryInfo(name = "Somalia", code = "SO"),
                CountryInfo(name = "South Africa", code = "ZA"),
                CountryInfo(name = "South Georgia and the South Sandwich Islands", code = "GS"),
                CountryInfo(name = "South Sudan", code = "SS"),
                CountryInfo(name = "Spain", code = "ES"),
                CountryInfo(name = "Sri Lanka", code = "LK"),
                CountryInfo(name = "Sudan", code = "SD"),
                CountryInfo(name = "Suriname", code = "SR"),
                CountryInfo(name = "Svalbard Jan Mayen", code = "SJ"),
                CountryInfo(name = "Sweden", code = "SE"),
                CountryInfo(name = "Switzerland", code = "CH"),
                CountryInfo(name = "Syrian Arab Republic", code = "SY"),
                CountryInfo(name = "Taiwan", code = "TW"),
                CountryInfo(name = "Tajikistan", code = "TJ"),
                CountryInfo(name = "Tanzania, United Republic of", code = "TZ"),
                CountryInfo(name = "Thailand", code = "TH"),
                CountryInfo(name = "Timor-Leste", code = "TL"),
                CountryInfo(name = "Togo", code = "TG"),
                CountryInfo(name = "Tokelau", code = "TK"),
                CountryInfo(name = "Tonga", code = "TO"),
                CountryInfo(name = "Trinidad and Tobago", code = "TT"),
                CountryInfo(name = "Tunisia", code = "TN"),
                CountryInfo(name = "Turkey", code = "TR"),
                CountryInfo(name = "Turkmenistan", code = "TM"),
                CountryInfo(name = "Turks and Caicos Islands", code = "TC"),
                CountryInfo(name = "Tuvalu", code = "TV"),
                CountryInfo(name = "Uganda", code = "UG"),
                CountryInfo(name = "Ukraine", code = "UA"),
                CountryInfo(name = "United Arab Emirates", code = "AE"),
                CountryInfo(name = "United Kingdom of Great Britain and Northern Ireland", code = "GB"),
                CountryInfo(name = "United States Minor Outlying Islands", code = "UM"),
                CountryInfo(name = "United States of America", code = "US"),
                CountryInfo(name = "Uruguay", code = "UY"),
                CountryInfo(name = "Uzbekistan", code = "UZ"),
                CountryInfo(name = "Vanuatu", code = "VU"),
                CountryInfo(name = "Venezuela (Bolivarian Republic of)", code = "VE"),
                CountryInfo(name = "Vietnam", code = "VN"),
                CountryInfo(name = "Virgin Islands (British)", code = "VG"),
                CountryInfo(name = "Virgin Islands", code = "VI"),
                CountryInfo(name = "Wallis and Futuna", code = "WF"),
                CountryInfo(name = "Western Sahara", code = "EH"),
                CountryInfo(name = "Yemen", code = "YE"),
                CountryInfo(name = "Zambia", code = "ZM"),
                CountryInfo(name = "Zimbabwe", code = "ZW"),
            )
    }
}