{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 202801,
          "sha512": "94a327180681eee45ea0f97b2a61d1453ce9190a64aae2f13f94f4943937356dec1307fec49631fe31f4a1a598e2cce314d8da1c24c0ad03d489dcf43beb3d19",
          "sha256": "7a5bd5136847e861ec913bb65895fc54a84bd5fa7a149be28105fe8f9562ef05",
          "sha1": "06213ced3ac8bc7ff59499794e9d8a44a7c690c3",
          "md5": "57c3620d0e0512a88e059561eaee4c27"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 202801,
          "sha512": "94a327180681eee45ea0f97b2a61d1453ce9190a64aae2f13f94f4943937356dec1307fec49631fe31f4a1a598e2cce314d8da1c24c0ad03d489dcf43beb3d19",
          "sha256": "7a5bd5136847e861ec913bb65895fc54a84bd5fa7a149be28105fe8f9562ef05",
          "sha1": "06213ced3ac8bc7ff59499794e9d8a44a7c690c3",
          "md5": "57c3620d0e0512a88e059561eaee4c27"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0-sources.jar",
          "url": "webview_flutter_android_profile-1.0-sources.jar",
          "size": 48068,
          "sha512": "27cabf6f6598b4d34891563fd540535eb5a5722bddc444f2a50b08ea78688a5091b408a18c260bd230699535f3cbc2a6fb5cef0b068375e02ec3353b8eaf4f0d",
          "sha256": "2ae3964f5df07386ca55a5c73218f909562514372d9ad40fdccc4f4fd9ab7dc4",
          "sha1": "be84071409f97d7332e1cad13f25b5827d8c9243",
          "md5": "e5d7ff13084172f104adf246873ae6c5"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0-javadoc.jar",
          "url": "webview_flutter_android_profile-1.0-javadoc.jar",
          "size": 637911,
          "sha512": "f29571cca1fefd11e515e2645cfb8c6f4b7b8d69a3d71fdbdc647eb4fe8a679765c7dee86ff88acc6f18633bca896689907e57f4805996fe8edff24fe75aade4",
          "sha256": "df27994d2f0bad55b2230b02573f782921acbe37bb14cadc8d315704efcd6bcb",
          "sha1": "24a4dbfdf5192fa3338148f7aa5a71d054fdd639",
          "md5": "3aa03a79f52e17d33b7daa0c1616cb9a"
        }
      ]
    }
  ]
}
