{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 202792,
          "sha512": "ea48d0d49e12db1198131644bf642bc31fbf47611240acef6531f3b603deb0e2ebf539f4ebcbb146e0b6bd1a9dfe00d4a0339f95fd74eb7559a98020e3cb6821",
          "sha256": "738d11a4379d63b973fd1277e61a36c708b6135fa20e000c25c6738a120534cc",
          "sha1": "70ee99a348b72665bdb804de9eecb5866185f2ee",
          "md5": "2d92cdde7563f9d11040dda1ea972304"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 202792,
          "sha512": "ea48d0d49e12db1198131644bf642bc31fbf47611240acef6531f3b603deb0e2ebf539f4ebcbb146e0b6bd1a9dfe00d4a0339f95fd74eb7559a98020e3cb6821",
          "sha256": "738d11a4379d63b973fd1277e61a36c708b6135fa20e000c25c6738a120534cc",
          "sha1": "70ee99a348b72665bdb804de9eecb5866185f2ee",
          "md5": "2d92cdde7563f9d11040dda1ea972304"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-sources.jar",
          "url": "webview_flutter_android_release-1.0-sources.jar",
          "size": 48068,
          "sha512": "27cabf6f6598b4d34891563fd540535eb5a5722bddc444f2a50b08ea78688a5091b408a18c260bd230699535f3cbc2a6fb5cef0b068375e02ec3353b8eaf4f0d",
          "sha256": "2ae3964f5df07386ca55a5c73218f909562514372d9ad40fdccc4f4fd9ab7dc4",
          "sha1": "be84071409f97d7332e1cad13f25b5827d8c9243",
          "md5": "e5d7ff13084172f104adf246873ae6c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.0-javadoc.jar",
          "size": 637839,
          "sha512": "2602655ab7391b96efd451b0c100342e9cff0c3bb8b6fb15260488d438d2608291c2f322feb06ce5462f65c5fbac74c74550680a1b0f75bb116747f8a61a7cfc",
          "sha256": "90fdf314a72fa392c5ea2e1ded9e9b0cf11111d7d202296017edee5e484d923c",
          "sha1": "96c24cc66058c5066ac01358b5d0841bf92903f6",
          "md5": "5cce2130ed14b58bcf159ee93765527a"
        }
      ]
    }
  ]
}
