{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 202792,
          "sha512": "ea48d0d49e12db1198131644bf642bc31fbf47611240acef6531f3b603deb0e2ebf539f4ebcbb146e0b6bd1a9dfe00d4a0339f95fd74eb7559a98020e3cb6821",
          "sha256": "738d11a4379d63b973fd1277e61a36c708b6135fa20e000c25c6738a120534cc",
          "sha1": "70ee99a348b72665bdb804de9eecb5866185f2ee",
          "md5": "2d92cdde7563f9d11040dda1ea972304"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 202792,
          "sha512": "ea48d0d49e12db1198131644bf642bc31fbf47611240acef6531f3b603deb0e2ebf539f4ebcbb146e0b6bd1a9dfe00d4a0339f95fd74eb7559a98020e3cb6821",
          "sha256": "738d11a4379d63b973fd1277e61a36c708b6135fa20e000c25c6738a120534cc",
          "sha1": "70ee99a348b72665bdb804de9eecb5866185f2ee",
          "md5": "2d92cdde7563f9d11040dda1ea972304"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-sources.jar",
          "url": "webview_flutter_android_release-1.0-sources.jar",
          "size": 48068,
          "sha512": "27cabf6f6598b4d34891563fd540535eb5a5722bddc444f2a50b08ea78688a5091b408a18c260bd230699535f3cbc2a6fb5cef0b068375e02ec3353b8eaf4f0d",
          "sha256": "2ae3964f5df07386ca55a5c73218f909562514372d9ad40fdccc4f4fd9ab7dc4",
          "sha1": "be84071409f97d7332e1cad13f25b5827d8c9243",
          "md5": "e5d7ff13084172f104adf246873ae6c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webview_flutter_android_release-1.0-javadoc.jar",
          "url": "webview_flutter_android_release-1.0-javadoc.jar",
          "size": 637842,
          "sha512": "7c6a963ce301c65e7c175f4b1adf3a10d0de4f412f7a024fb15ea659ed49f92dccc0bcbd290efd853d6e79e071fa2cd403aeaf0945a38b937c9e588c01f9ef90",
          "sha256": "fb3fb54f0904724d24b2f2041d68d8d17c636fbd427805c83b46a7a70261180f",
          "sha1": "29fcaab70fa26bfae468d9d83db1f4ca120b328b",
          "md5": "7440e387eb4cb9db0f9cc8a4c57d98e2"
        }
      ]
    }
  ]
}
