{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e672b006cb34c921db85b8e2f482ed3144a4574b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-1.0.aar",
          "url": "pay_android_debug-1.0.aar",
          "size": 23510,
          "sha512": "52b3a7e41146952511da92f43965c2102ba92a603da45a28e7a1efcfbab7d8bf220e3aa656f20f26678f2bd6aa04b3a0c730ff0b3166ac493cd1fba95225b3a9",
          "sha256": "fab61be293b3335bbbed5db6e2b682fdd4fbea0f297cc74898ec7ea2e70f4fdd",
          "sha1": "f1d1544fd1b6432becaace1bc2f319e2ded57f97",
          "md5": "58424819969caad2409a0132f5375f27"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e672b006cb34c921db85b8e2f482ed3144a4574b"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_debug-1.0.aar",
          "url": "pay_android_debug-1.0.aar",
          "size": 23510,
          "sha512": "52b3a7e41146952511da92f43965c2102ba92a603da45a28e7a1efcfbab7d8bf220e3aa656f20f26678f2bd6aa04b3a0c730ff0b3166ac493cd1fba95225b3a9",
          "sha256": "fab61be293b3335bbbed5db6e2b682fdd4fbea0f297cc74898ec7ea2e70f4fdd",
          "sha1": "f1d1544fd1b6432becaace1bc2f319e2ded57f97",
          "md5": "58424819969caad2409a0132f5375f27"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_debug-1.0-sources.jar",
          "url": "pay_android_debug-1.0-sources.jar",
          "size": 10537,
          "sha512": "bd41922cad864f7255f0a140aa54cd69534fc190b384a6047757e80b375a5500e06c1ba127f8b30c0953f717c45029f319ba1e7c5b197b262ed8969c61ddd733",
          "sha256": "ed92413e0d394b18f77c128c15e8a08ebbcc7d14492a3c9815aa0e51972cc6a6",
          "sha1": "c538b625e39b2e43b25b9fce76e850520add890b",
          "md5": "2bae8a6ef90c9131b6c6cbf09b0e4076"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_debug-1.0-javadoc.jar",
          "url": "pay_android_debug-1.0-javadoc.jar",
          "size": 307740,
          "sha512": "13b3a668acf960638eaee22a85cd6bdb2b869d1d233978409f45d3d54a765511bccbde217224216a4440a102272415eaa46620e602b17290083ff24d22792efc",
          "sha256": "5fd05c04c2e42160c3dd3ca1a4db21aa53bfe39cbe062e3eb5773ce463d16ad4",
          "sha1": "77c91e0081d95deae153e5e88e982a1f743ad059",
          "md5": "882479f3780136ba595f4aa861c5f858"
        }
      ]
    }
  ]
}
