{
  "formatVersion": "1.1",
  "component": {
    "group": "com.prongbang.screen_protector",
    "module": "screen_protector_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_release-1.0.aar",
          "url": "screen_protector_release-1.0.aar",
          "size": 3183,
          "sha512": "0b861efdccf62cbf0d6bab2a32a04ed9ae15d58bf40997757399af7a1f9786421c8b62cd3278924ca2ea57cca8ca956d0335498ad413bbcfec85a4b002121a2e",
          "sha256": "a772b05036d955e6b62c18277202488c159dc51fd1b9ef086a563ea49307d908",
          "sha1": "6fb05d2a9bdfe6fd9eed1a579e4007006a05bc43",
          "md5": "9fa9e591ccffe9247f8799c69b220a85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_release-1.0.aar",
          "url": "screen_protector_release-1.0.aar",
          "size": 3183,
          "sha512": "0b861efdccf62cbf0d6bab2a32a04ed9ae15d58bf40997757399af7a1f9786421c8b62cd3278924ca2ea57cca8ca956d0335498ad413bbcfec85a4b002121a2e",
          "sha256": "a772b05036d955e6b62c18277202488c159dc51fd1b9ef086a563ea49307d908",
          "sha1": "6fb05d2a9bdfe6fd9eed1a579e4007006a05bc43",
          "md5": "9fa9e591ccffe9247f8799c69b220a85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_protector_release-1.0-sources.jar",
          "url": "screen_protector_release-1.0-sources.jar",
          "size": 1410,
          "sha512": "065179809df630ea71a66f33df4c4be29e52dcbf896fe4b3129742e505ecd8bf19038a6b149150ae321edf568ca67bf260fb0861b023e936321d308d9d9f982c",
          "sha256": "5334cd3d389b31fe8847e35c47c8af67a2d63660e210f52b507266958e93ae0f",
          "sha1": "d698d4f2e522a3e617149a14c79f2eb15b87c60d",
          "md5": "6cd694b12c15e8dff05a159609dea637"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_protector_release-1.0-javadoc.jar",
          "url": "screen_protector_release-1.0-javadoc.jar",
          "size": 262695,
          "sha512": "f13a22daeb1d0ad43542946cce4b3cbf03190828243f24c34f492a67a6edc95586f3f53d6fb30bce950d3ad96a58e9378c269fe8b82453f234ee51c9b734aff8",
          "sha256": "8c87382033214d0b3161841c7d8523dfefe8cc58f7e192560532c96527d25657",
          "sha1": "c7cc6f979b290794d2b4e1f3165ca7eb53022320",
          "md5": "3c280892b5e46d404a327ddf9a00de78"
        }
      ]
    }
  ]
}
