{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 22530,
          "sha512": "e55bf9629261b14ca1c4648eb7916008967d9a0583fa2cde1eafdfdceee6f69d208d9e02d4f4607590bf58c4576e1dbc9fcca004c7aa594983878103aa1b3ce8",
          "sha256": "b6584332cfeb30b4d57a4638d3956287f729daf1849eadb2cbb23a8f879e14cb",
          "sha1": "ed2bee61363a632001b1357592642a6418752e63",
          "md5": "89d6e9e04c821c3bc1864644463d8fb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf56914b326edb0ccb123ffdc60f00060bd513fa"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.aar",
          "url": "url_launcher_android_release-1.0.aar",
          "size": 22530,
          "sha512": "e55bf9629261b14ca1c4648eb7916008967d9a0583fa2cde1eafdfdceee6f69d208d9e02d4f4607590bf58c4576e1dbc9fcca004c7aa594983878103aa1b3ce8",
          "sha256": "b6584332cfeb30b4d57a4638d3956287f729daf1849eadb2cbb23a8f879e14cb",
          "sha1": "ed2bee61363a632001b1357592642a6418752e63",
          "md5": "89d6e9e04c821c3bc1864644463d8fb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0-sources.jar",
          "url": "url_launcher_android_release-1.0-sources.jar",
          "size": 9404,
          "sha512": "5ac088da042502a3f5c39f955abf092c6ed490da35464d60eef45dfe1262eaa3143a53d77fbc218d037582b780c5421fdaf8847482847de8b1bffa8ceaf3468e",
          "sha256": "fc09a1ed942bde1578570cc2f2198e7e9b51c87bfa35bb88eb9343b3fc7d83c3",
          "sha1": "7a87e8d621aa50c862331ee6827305b6c76c57fd",
          "md5": "1266bbfa8f2588435497db7b9ffe2c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0-javadoc.jar",
          "url": "url_launcher_android_release-1.0-javadoc.jar",
          "size": 332548,
          "sha512": "ec0580071fd509910ff57c51fac17efb28d7274fb0360f81025bc2594779e06afd93e64c123d620ce209b7aa9deedd4b8c2aded151c1160089b1cde1f34b0f19",
          "sha256": "ef5fda21951006fe8e4f60a484ebc4bf2f003c8d6f60575e915e1bdb44688796",
          "sha1": "1a77de3f0d6a157e37d592bec2a02f5563de99b6",
          "md5": "9be176cdb10a13f0a2dedef749e72920"
        }
      ]
    }
  ]
}
