{
  "formatVersion": "1.1",
  "component": {
    "group": "com.prongbang.screen_protector",
    "module": "screen_protector_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e672b006cb34c921db85b8e2f482ed3144a4574b"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_debug-1.0.aar",
          "url": "screen_protector_debug-1.0.aar",
          "size": 3286,
          "sha512": "a5b205bae445945398e73283d1ca8e676927d41d3c302e7f2564068c6eb7ef4e17e6183cd73ac068d1ed4cba7e509f4d718964551d9b111ffc75a895d659f4b3",
          "sha256": "5635df2e104220e3c45e89db58a20ca5abbdab77866afbd5bea3df9401b3be23",
          "sha1": "81297ca777aef69c12eb8ef50a142b557ba82062",
          "md5": "2862f44884127fae864e96240a387745"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-e672b006cb34c921db85b8e2f482ed3144a4574b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_debug-1.0.aar",
          "url": "screen_protector_debug-1.0.aar",
          "size": 3286,
          "sha512": "a5b205bae445945398e73283d1ca8e676927d41d3c302e7f2564068c6eb7ef4e17e6183cd73ac068d1ed4cba7e509f4d718964551d9b111ffc75a895d659f4b3",
          "sha256": "5635df2e104220e3c45e89db58a20ca5abbdab77866afbd5bea3df9401b3be23",
          "sha1": "81297ca777aef69c12eb8ef50a142b557ba82062",
          "md5": "2862f44884127fae864e96240a387745"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_protector_debug-1.0-sources.jar",
          "url": "screen_protector_debug-1.0-sources.jar",
          "size": 1410,
          "sha512": "065179809df630ea71a66f33df4c4be29e52dcbf896fe4b3129742e505ecd8bf19038a6b149150ae321edf568ca67bf260fb0861b023e936321d308d9d9f982c",
          "sha256": "5334cd3d389b31fe8847e35c47c8af67a2d63660e210f52b507266958e93ae0f",
          "sha1": "d698d4f2e522a3e617149a14c79f2eb15b87c60d",
          "md5": "6cd694b12c15e8dff05a159609dea637"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen_protector_debug-1.0-javadoc.jar",
          "url": "screen_protector_debug-1.0-javadoc.jar",
          "size": 262695,
          "sha512": "f13a22daeb1d0ad43542946cce4b3cbf03190828243f24c34f492a67a6edc95586f3f53d6fb30bce950d3ad96a58e9378c269fe8b82453f234ee51c9b734aff8",
          "sha256": "8c87382033214d0b3161841c7d8523dfefe8cc58f7e192560532c96527d25657",
          "sha1": "c7cc6f979b290794d2b4e1f3165ca7eb53022320",
          "md5": "3c280892b5e46d404a327ddf9a00de78"
        }
      ]
    }
  ]
}
