{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pay_android",
    "module": "pay_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_release-1.0.aar",
          "url": "pay_android_release-1.0.aar",
          "size": 22599,
          "sha512": "c39a057aa0008ebef3fad11490cf2dbafcf1ee1fffe9d0620e959e74d6d291d5aa6a9abecaabbeeff85a7b03717e2b08fd26bfff502f9703b95b456aea946fb9",
          "sha256": "b64740822e18ec79692db537dd1bffbc1db788f59b6109e3bce06b185ea41359",
          "sha1": "620228dc565e063887af770bc7e644efb99226c1",
          "md5": "1677fb0bdd334f2d0f91d0e307ad4914"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pay_android_release-1.0.aar",
          "url": "pay_android_release-1.0.aar",
          "size": 22599,
          "sha512": "c39a057aa0008ebef3fad11490cf2dbafcf1ee1fffe9d0620e959e74d6d291d5aa6a9abecaabbeeff85a7b03717e2b08fd26bfff502f9703b95b456aea946fb9",
          "sha256": "b64740822e18ec79692db537dd1bffbc1db788f59b6109e3bce06b185ea41359",
          "sha1": "620228dc565e063887af770bc7e644efb99226c1",
          "md5": "1677fb0bdd334f2d0f91d0e307ad4914"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_release-1.0-sources.jar",
          "url": "pay_android_release-1.0-sources.jar",
          "size": 10537,
          "sha512": "bd41922cad864f7255f0a140aa54cd69534fc190b384a6047757e80b375a5500e06c1ba127f8b30c0953f717c45029f319ba1e7c5b197b262ed8969c61ddd733",
          "sha256": "ed92413e0d394b18f77c128c15e8a08ebbcc7d14492a3c9815aa0e51972cc6a6",
          "sha1": "c538b625e39b2e43b25b9fce76e850520add890b",
          "md5": "2bae8a6ef90c9131b6c6cbf09b0e4076"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pay_android_release-1.0-javadoc.jar",
          "url": "pay_android_release-1.0-javadoc.jar",
          "size": 307740,
          "sha512": "13b3a668acf960638eaee22a85cd6bdb2b869d1d233978409f45d3d54a765511bccbde217224216a4440a102272415eaa46620e602b17290083ff24d22792efc",
          "sha256": "5fd05c04c2e42160c3dd3ca1a4db21aa53bfe39cbe062e3eb5773ce463d16ad4",
          "sha1": "77c91e0081d95deae153e5e88e982a1f743ad059",
          "md5": "882479f3780136ba595f4aa861c5f858"
        }
      ]
    }
  ]
}
