name: Distribute Android App Firebase

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build and distribute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Configure Firebase Credentials
        env:
          FIREBASE_SA_JSON_B64: ${{ secrets.FIREBASE_SA_JSON_B64 }}
        run: |
          echo "$FIREBASE_SA_JSON_B64" | base64 --decode > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV        

      - name: Build project
        run: ./gradlew app:assembleKotlinStaging
        env:
          OMISE_PUBLIC_KEY: ${{ secrets.OMISE_PUBLIC_KEY }}
          GOOGLE_PAY_MERCHANT_ID: ${{ secrets.GOOGLE_PAY_MERCHANT_ID }}

      - name: Rename APK with commit hash
        run: |
          cp app/build/outputs/apk/kotlinStaging/release/app-kotlin-staging-release.apk \
          app-kotlin-staging-release-${{ github.sha }}.apk

      - name: Distribute to Firebase
        env:
          FIREBASE_APP_ID:             ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_DISTRIBUTION_GROUP: ${{ secrets.FIREBASE_DISTRIBUTION_GROUP }}
        run: |
          firebase appdistribution:distribute "app-kotlin-staging-release-${{ github.sha }}.apk" \
            --app    "$FIREBASE_APP_ID" \
            --groups "$FIREBASE_DISTRIBUTION_GROUP" \
            --release-notes "Built on • $(date +%Y-%m-%d) • from hash: ${{ github.sha }}"

